// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'


const SUPABASE_URL = 'https://lsouwwmarglclztmyjla.supabase.co'
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxzb3V3d21hcmdsY2x6dG15amxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMTgwMzIsImV4cCI6MjA2MDU5NDAzMn0.ei2ZNXFG8HHpIqZAwktryE3iXmjcLJIpHqUMDVlwq68'

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  realtime: {
    params: {
      eventsPerSecond: 10
    }
  }
})
